ALTER TABLE `categories`
ADD COLUMN `emoji` VARCHAR(255) DEFAULT NULL,
ADD COLUMN `logo` VARCHAR(255) DEFAULT NULL,
ADD COLUMN `category_type` VARCHAR(255) DEFAULT NULL;

ALTER TABLE `sub_categories`
MODIFY COLUMN `description` TEXT DEFAULT NULL;
